//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace yoGomee.Emulator.ws {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmulatorSoap", Namespace="http://tempuri.org/")]
    public partial class Emulator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RunApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApplicationListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Emulator() {
            this.Url = global::yoGomee.Emulator.Properties.Settings.Default.yoGomee_Emulator_ws_Emulator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RunApplicationCompletedEventHandler RunApplicationCompleted;
        
        /// <remarks/>
        public event GetApplicationListCompletedEventHandler GetApplicationListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunApplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExecutionResponse RunApplication(string ApplicationName) {
            object[] results = this.Invoke("RunApplication", new object[] {
                        ApplicationName});
            return ((ExecutionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RunApplicationAsync(string ApplicationName) {
            this.RunApplicationAsync(ApplicationName, null);
        }
        
        /// <remarks/>
        public void RunApplicationAsync(string ApplicationName, object userState) {
            if ((this.RunApplicationOperationCompleted == null)) {
                this.RunApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunApplicationOperationCompleted);
            }
            this.InvokeAsync("RunApplication", new object[] {
                        ApplicationName}, this.RunApplicationOperationCompleted, userState);
        }
        
        private void OnRunApplicationOperationCompleted(object arg) {
            if ((this.RunApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunApplicationCompleted(this, new RunApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApplicationList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetApplicationList() {
            object[] results = this.Invoke("GetApplicationList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetApplicationListAsync() {
            this.GetApplicationListAsync(null);
        }
        
        /// <remarks/>
        public void GetApplicationListAsync(object userState) {
            if ((this.GetApplicationListOperationCompleted == null)) {
                this.GetApplicationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApplicationListOperationCompleted);
            }
            this.InvokeAsync("GetApplicationList", new object[0], this.GetApplicationListOperationCompleted, userState);
        }
        
        private void OnGetApplicationListOperationCompleted(object arg) {
            if ((this.GetApplicationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApplicationListCompleted(this, new GetApplicationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecutionResponse {
        
        private int errorLineNumberField;
        
        private string debugTextField;
        
        private YogoAction yogoActionField;
        
        /// <remarks/>
        public int ErrorLineNumber {
            get {
                return this.errorLineNumberField;
            }
            set {
                this.errorLineNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DebugText {
            get {
                return this.debugTextField;
            }
            set {
                this.debugTextField = value;
            }
        }
        
        /// <remarks/>
        public YogoAction YogoAction {
            get {
                return this.yogoActionField;
            }
            set {
                this.yogoActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YogoAction {
        
        private ActionType actionTypeField;
        
        private string textToDisplayField;
        
        private string imageUrlField;
        
        private Sms smsToSendField;
        
        private string urlToNavigateToField;
        
        /// <remarks/>
        public ActionType ActionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TextToDisplay {
            get {
                return this.textToDisplayField;
            }
            set {
                this.textToDisplayField = value;
            }
        }
        
        /// <remarks/>
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        public Sms SmsToSend {
            get {
                return this.smsToSendField;
            }
            set {
                this.smsToSendField = value;
            }
        }
        
        /// <remarks/>
        public string UrlToNavigateTo {
            get {
                return this.urlToNavigateToField;
            }
            set {
                this.urlToNavigateToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ActionType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Sms,
        
        /// <remarks/>
        SoundPlay,
        
        /// <remarks/>
        SoundRecord,
        
        /// <remarks/>
        VideoPlay,
        
        /// <remarks/>
        VideoRecord,
        
        /// <remarks/>
        Photo,
        
        /// <remarks/>
        Call,
        
        /// <remarks/>
        Browser,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sms {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RunApplicationCompletedEventHandler(object sender, RunApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExecutionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExecutionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetApplicationListCompletedEventHandler(object sender, GetApplicationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApplicationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApplicationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591