/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.yogome;

public final class R {
    public static final class array {
        public static final int audioEnds=0x7f060002;
        public static final int gomee_types=0x7f060000;
        public static final int imageEnds=0x7f060001;
        public static final int packageEnds=0x7f060003;
        public static final int textEnds=0x7f060004;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int add=0x7f020000;
        public static final int alert_dialog_icon=0x7f020001;
        public static final int circscreen=0x7f020002;
        public static final int close=0x7f020003;
        public static final int delete=0x7f020004;
        public static final int files=0x7f020005;
        public static final int folder32=0x7f020006;
        public static final int gomee_list=0x7f020007;
        public static final int icon=0x7f020008;
        public static final int icon48x48_1=0x7f020009;
        public static final int icon48x48_2=0x7f02000a;
        public static final int image=0x7f02000b;
        public static final int image32=0x7f02000c;
        public static final int link=0x7f02000d;
        public static final int map_sat=0x7f02000e;
        public static final int marker=0x7f02000f;
        public static final int mural=0x7f020010;
        public static final int my_position=0x7f020011;
        public static final int new_gomee=0x7f020012;
        public static final int preferences=0x7f020013;
        public static final int text=0x7f020014;
        public static final int text32=0x7f020015;
        public static final int theme_alert=0x7f020016;
        public static final int uponelevel=0x7f020017;
        public static final int video=0x7f020018;
        public static final int wall=0x7f020019;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f090008;
        public static final int TextView01=0x7f090006;
        public static final int icon=0x7f09000b;
        public static final int img=0x7f090000;
        public static final int imgThumb=0x7f090009;
        public static final int map=0x7f09000c;
        public static final int txtDate=0x7f090005;
        public static final int txtDesc=0x7f090007;
        public static final int txtDescription=0x7f090002;
        public static final int txtTitle=0x7f090001;
        public static final int widget0=0x7f09000a;
        public static final int widget28=0x7f090004;
        public static final int widget29=0x7f090003;
        public static final int zoom=0x7f09000d;
    }
    public static final class layout {
        public static final int gomee_image=0x7f030000;
        public static final int gomee_text=0x7f030001;
        public static final int goome_popup=0x7f030002;
        public static final int main=0x7f030003;
        public static final int yogoalert=0x7f030004;
        public static final int yogomap=0x7f030005;
    }
    public static final class raw {
        public static final int proximity_alert=0x7f050000;
    }
    public static final class string {
        public static final int access=0x7f070017;
        public static final int ad=0x7f070006;
        public static final int add_gomee=0x7f070003;
        public static final int alert_dialog_cancel=0x7f07000d;
        public static final int alert_dialog_ok=0x7f07000c;
        public static final int app_name=0x7f070001;
        public static final int cancel=0x7f070009;
        public static final int circumgyrate=0x7f070002;
        public static final int current_dir=0x7f070004;
        public static final int exit=0x7f070005;
        public static final int gomee=0x7f07000f;
        public static final int gomee_list=0x7f070012;
        public static final int gomee_murales=0x7f070011;
        public static final int hello=0x7f070000;
        public static final int msg_delete_gomee=0x7f07000b;
        public static final int msg_no_location=0x7f070010;
        public static final int ok=0x7f070008;
        public static final int password=0x7f070016;
        public static final int proximity=0x7f070019;
        public static final int proximity_radius=0x7f070018;
        public static final int remember=0x7f07001a;
        public static final int ringtone_alert=0x7f070014;
        public static final int title_delete_gomee=0x7f07000a;
        public static final int title_gomee_type=0x7f07000e;
        public static final int up_one_level=0x7f070007;
        public static final int username=0x7f070015;
        public static final int you_are_in=0x7f070013;
    }
    public static final class style {
        public static final int Theme=0x7f080000;
        public static final int Theme_Alert=0x7f080001;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
